services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: balance
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: balance
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: